"""
Pydantic models for Resume-Job Matching synthetic data generation.

This module defines the data structure for resumes, job descriptions, and their
pairings that will be generated by the LLM and validated throughout the project phases.

About Pydantic:
Pydantic is a Python library for data validation using type hints. It ensures
data matches a defined structure and automatically validates types, converts
values when possible, and raises clear errors for invalid data. In this project,
Pydantic models enforce that LLM-generated responses contain all required fields
with correct types, guaranteeing consistent, valid synthetic data.
"""

from enum import Enum

from pydantic import BaseModel, Field, field_validator, ConfigDict, ValidationInfo
from pydantic.networks import EmailStr
from typing import List, Optional
from datetime import date, datetime
from uuid import uuid4
import phonenumbers


class FitLevel(str, Enum):
    """Controlled fit level labels for resume-job pair quality."""

    EXCELLENT = "excellent"
    GOOD = "good"
    PARTIAL = "partial"
    POOR = "poor"
    COMPLETE_MISMATCH = "complete_mismatch"


class ProficiencyLevel(str, Enum):
    """Controlled proficiency levels for skills."""

    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
    EXPERT = "expert"


class SeniorityLevel(str, Enum):
    """Controlled seniority levels for role requirements."""

    ENTRY_LEVEL = "entry_level"
    MID_LEVEL = "mid_level"
    SENIOR = "senior"


class ContactInfo(BaseModel):
    """
    Schema for contact information in a resume.
    """
    
    name: str = Field(
        ...,
        description="Full name of the person",
        min_length=2
    )
    
    email: EmailStr = Field(
        ...,
        description="Email address"
    )

    phone_region: Optional[str] = Field(
        None,
        description="ISO 3166-1 alpha-2 country code used to parse non-E.164 numbers (e.g., US, AU, GB)"
    )
    
    phone: str = Field(
        ...,
        description="Phone number"
    )
    
    location: str = Field(
        ...,
        description="City, State or Country",
        min_length=3
    )
    
    @field_validator('email')
    @classmethod
    def normalize_email(cls, v):
        """Normalize email to lowercase after built-in validation"""
        return v.lower()  # EmailStr handles validation, we just normalize

    @field_validator('phone_region')
    @classmethod
    def normalize_phone_region(cls, v):
        """Normalize and validate phone region code."""
        if v is None:
            return v
        region = v.strip().upper()
        if len(region) != 2 or not region.isalpha():
            raise ValueError('phone_region must be a 2-letter ISO country code')
        return region
    
    @field_validator('phone')
    @classmethod
    def validate_phone(cls, v, info: ValidationInfo):
        """Validate phone number and normalize to E164 format."""
        if any(ch.isalpha() for ch in v):
            raise ValueError('Invalid phone number format')

        if v.strip().startswith('+'):
            region = None
        else:
            region = info.data.get('phone_region')
            if not region:
                raise ValueError('phone_region is required for non-E.164 phone numbers')

        try:
            parsed_number = phonenumbers.parse(v, region)
        except phonenumbers.NumberParseException as exc:
            raise ValueError('Invalid phone number format') from exc

        if not phonenumbers.is_possible_number(parsed_number):
            raise ValueError('Invalid phone number format')

        if not phonenumbers.is_valid_number(parsed_number):
            raise ValueError('Invalid phone number format')

        return phonenumbers.format_number(
            parsed_number,
            phonenumbers.PhoneNumberFormat.E164,
        )


class Education(BaseModel):
    """
    Schema for education entry in a resume.
    """
    
    institution: str = Field(
        ...,
        description="Name of educational institution",
        min_length=3
    )
    
    degree: str = Field(
        ...,
        description="Degree obtained or pursuing",
        min_length=3
    )
    
    field_of_study: str = Field(
        ...,
        description="Major or field of study",
        min_length=3
    )
    
    graduation_year: Optional[int] = Field(
        None,
        description="Year of graduation",
        ge=1950,
        le=2030
    )
    
    gpa: Optional[float] = Field(
        None,
        description="Grade Point Average",
        ge=0.0,
        le=4.0
    )


class Experience(BaseModel):
    """
    Schema for work experience entry in a resume.
    """
    
    company: str = Field(
        ...,
        description="Company name",
        min_length=2
    )
    
    position: str = Field(
        ...,
        description="Job title or position",
        min_length=2
    )
    
    start_date: date = Field(
        ...,
        description="Start date in ISO format (YYYY-MM-DD)"
    )
    
    end_date: Optional[date] = Field(
        None,
        description="End date in ISO format (YYYY-MM-DD); None indicates currently employed"
    )
    
    description: str = Field(
        ...,
        description="Job description and responsibilities",
        min_length=20
    )
    
    achievements: List[str] = Field(
        default_factory=list,
        description="List of key achievements"
    )
    
    @field_validator('end_date')
    @classmethod
    def validate_date_sequence(cls, v, info):
        """Validate end_date comes after start_date"""
        if v is None:
            return v
            
        # Get start_date from other fields using info.data
        start_date = info.data.get('start_date')
        if start_date is None:
            return v
        
        if v <= start_date:
            raise ValueError('end_date must be after start_date')
            
        return v


class Skill(BaseModel):
    """
    Schema for individual skill entry.
    """
    
    name: str = Field(
        ...,
        description="Skill name",
        min_length=2
    )
    
    category: str = Field(
        ...,
        description="Skill category (e.g., 'Programming', 'Design', 'Languages')",
        min_length=3
    )
    
    proficiency: ProficiencyLevel = Field(
        ...,
        description="Proficiency level"
    )


class ResumeMetadata(BaseModel):
    """
    Schema for resume metadata.
    """
    
    trace_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Trace identifier for linking generated resume artifacts",
        min_length=3
    )

    generated_at: datetime = Field(
        default_factory=datetime.now,
        description="When the resume was generated"
    )

    prompt_template: str = Field(
        default="baseline_v1",
        description="Prompt template identifier used for generation",
        min_length=3
    )

    fit_level: Optional[FitLevel] = Field(
        None,
        description="Target fit level used during generation"
    )

    writing_style: str = Field(
        default="professional",
        description="Writing style label for the generated resume",
        min_length=3
    )

    used_fallback: bool = Field(
        default=False,
        description="Whether this resume used deterministic fallback generation instead of direct LLM output"
    )


class Resume(BaseModel):
    """
    Schema for a complete resume.
    
    This model enforces the structure of synthetic resume data, ensuring
    all required fields are present with correct types.
    """
    
    contact_info: ContactInfo = Field(
        ...,
        description="Contact information"
    )
    
    education: List[Education] = Field(
        ...,
        description="List of education entries",
        min_length=1
    )
    
    experience: List[Experience] = Field(
        ...,
        description="List of work experience entries",
        min_length=1
    )
    
    skills: List[Skill] = Field(
        ...,
        description="List of skills",
        min_length=3
    )
    
    metadata: ResumeMetadata = Field(
        default_factory=ResumeMetadata,
        description="Resume metadata"
    )
    
    summary: Optional[str] = Field(
        None,
        description="Professional summary or objective",
        min_length=20
    )


class JobRequirements(BaseModel):
    """
    Schema for job requirements.
    """
    
    required_skills: List[str] = Field(
        ...,
        description="List of required skills",
        min_length=1
    )
    
    preferred_skills: List[str] = Field(
        default_factory=list,
        description="List of preferred but not required skills"
    )
    
    experience_level: SeniorityLevel = Field(
        ...,
        description="Required experience level"
    )
    
    education_requirements: str = Field(
        ...,
        description="Education requirements",
        min_length=5
    )
    
    years_experience: Optional[int] = Field(
        None,
        description="Minimum years of experience required",
        ge=0,
        le=30
    )


class JobMetadata(BaseModel):
    """
    Schema for job description metadata.
    """
    
    trace_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Trace identifier for linking generated job artifacts",
        min_length=3
    )

    generated_at: datetime = Field(
        default_factory=datetime.now,
        description="When the job description was generated"
    )

    is_niche_role: bool = Field(
        default=False,
        description="Whether this role is niche/specialized"
    )

    used_fallback: bool = Field(
        default=False,
        description="Whether this job used deterministic fallback generation instead of direct LLM output"
    )


class JobDescription(BaseModel):
    """
    Schema for a complete job description.
    
    This model enforces the structure of synthetic job description data.
    """
    
    company: str = Field(
        ...,
        description="Company name",
        min_length=2
    )

    industry: str = Field(
        ...,
        description="Industry for the company",
        min_length=2
    )

    company_size: str = Field(
        ...,
        description="Company size category",
        min_length=2
    )
    
    position: str = Field(
        ...,
        description="Job title",
        min_length=2
    )
    
    location: str = Field(
        ...,
        description="Job location",
        min_length=3
    )
    
    description: str = Field(
        ...,
        description="Job description and responsibilities",
        min_length=50
    )
    
    requirements: JobRequirements = Field(
        ...,
        description="Job requirements"
    )
    
    metadata: JobMetadata = Field(
        ...,
        description="Job metadata"
    )
    
    salary_range: Optional[str] = Field(
        None,
        description="Salary range",
        min_length=5
    )
    
    benefits: Optional[List[str]] = Field(
        default_factory=list,
        description="List of benefits"
    )


class ResumeJobPair(BaseModel):
    """
    Schema for pairing a resume with a job description.
    
    This model represents the relationship between a resume and job
    for analysis and matching purposes.
    """
    
    resume: Resume = Field(
        ...,
        description="The resume data"
    )
    
    job_description: JobDescription = Field(
        ...,
        description="The job description data"
    )
    
    fit_level: Optional[FitLevel] = Field(
        None,
        description="Assessed fit level"
    )
    
    trace_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for this pairing",
        min_length=3
    )
    
    analysis_date: datetime = Field(
        default_factory=datetime.now,
        description="When this pairing was analyzed"
    )
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "resume": {
                    "contact_info": {
                        "name": "John Doe",
                        "email": "john.doe@example.com",
                        "phone_region": "US",
                        "phone": "555-123-4567",
                        "location": "San Francisco, CA"
                    },
                    "education": [
                        {
                            "institution": "Stanford University",
                            "degree": "Bachelor of Science",
                            "field_of_study": "Computer Science",
                            "graduation_year": 2020,
                            "gpa": 3.8
                        }
                    ],
                    "experience": [
                        {
                            "company": "Tech Corp",
                            "position": "Software Engineer",
                            "start_date": "2020-06-01",
                            "end_date": "2023-01-01",
                            "description": "Developed web applications using React and Node.js",
                            "achievements": ["Reduced page load time by 40%", "Led team of 3 developers"]
                        }
                    ],
                    "skills": [
                        {"name": "Python", "category": "Programming", "proficiency": "expert"},
                        {"name": "JavaScript", "category": "Programming", "proficiency": "expert"},
                        {"name": "React", "category": "Programming", "proficiency": "expert"}
                    ],
                    "metadata": {
                        "trace_id": "resume-001",
                        "generated_at": "2024-01-15T10:00:00Z",
                        "prompt_template": "achievement_focused_v1",
                        "fit_level": "good",
                        "writing_style": "achievement_focused",
                        "used_fallback": False
                    }
                },
                "job_description": {
                    "company": "StartupXYZ",
                    "industry": "Software",
                    "company_size": "51-200",
                    "position": "Senior Software Engineer",
                    "location": "San Francisco, CA",
                    "description": "We are looking for an experienced software engineer to join our growing team...",
                    "requirements": {
                        "required_skills": ["Python", "JavaScript", "React"],
                        "preferred_skills": ["Docker", "AWS"],
                        "experience_level": "senior",
                        "education_requirements": "Bachelor's degree in Computer Science or related field",
                        "years_experience": 5
                    },
                    "metadata": {
                        "trace_id": "job-001",
                        "generated_at": "2024-01-15T10:00:00Z",
                        "is_niche_role": False,
                        "used_fallback": False
                    }
                },
                "fit_level": "good",
                "trace_id": "pair-001"
            }
        }
    )
